apiVersion: v1
kind: Service
metadata:
  name: {{ include "alien-shooter.fullname" . }}
  labels:
    {{- include "alien-shooter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "alien-shooter.selectorLabels" . | nindent 4 }}